package constants

var SkillsThemes = map[string]string{
	"SQL":           "DataBase",
	"DevOps":        "IT",
	"Python":        "programming language",
	"AWS":           "cloud",
	"Linux":         "operating system",
	"Spark":         "Technology",
	"Agile":         "project management",
	"Windows":       "operating system",
	"Azure":         "cloud",
	"C++":           "programming language",
	"C":             "programming language",
	"ReactJS":       "Front-end development",
	"Go":            "programming language",
	"C#":            "programming language",
	"Node.js":       "Back-end development",
	"Scala":         "programming language",
	"JavaScript":    "programming language",
	"J2EE":          "Back-end development",
	".NET":          "Back-end development",
	"UNIX":          "operating system",
	"Elasticsearch": "search engine",
	"OOP":           "paradigm ",
	"GitHub":        "Technology",
	"JSON":          "Technology",
	"React":         "Front-end development",
	"Spring Boot":   "Back-end development",
	"DynamoDB":      "DataBase",
	"Git":           "Technology",
	"Docker":        "Technology",
	"NoSQL":         "DataBase",
	"SOAP":          "paradigm ",
	"PHP":           "programming language",
	"PostgreSQL":    "DataBase",
	"Big data":      "paradigm ",
	"Kubernetes":    "Technology",
	"Jira":          "Technology",
}
