FROM python:3.8-slim-buster

WORKDIR /app

COPY data_loader/requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY graph_driver graph_driver

COPY graph_query_builder graph_query_builder

COPY data_loader api

ENV FLASK_APP=api.api

ENV NEO4J_USERNAME=

ENV NEO4J_PASSWORD=

ENV NEO4J_URL=bolt://localhost:7687

EXPOSE 5000

CMD flask run --host=0.0.0.0
