// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Title                string        `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Company              string        `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Logo                 string        `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	Link                 string        `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	Location             string        `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Skills               []*Job_Skills `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Job) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Job) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Job) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Job) GetSkills() []*Job_Skills {
	if m != nil {
		return m.Skills
	}
	return nil
}

type Job_Skills struct {
	Skill                string   `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	Theme                string   `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job_Skills) Reset()         { *m = Job_Skills{} }
func (m *Job_Skills) String() string { return proto.CompactTextString(m) }
func (*Job_Skills) ProtoMessage()    {}
func (*Job_Skills) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0, 0}
}

func (m *Job_Skills) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job_Skills.Unmarshal(m, b)
}
func (m *Job_Skills) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job_Skills.Marshal(b, m, deterministic)
}
func (m *Job_Skills) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job_Skills.Merge(m, src)
}
func (m *Job_Skills) XXX_Size() int {
	return xxx_messageInfo_Job_Skills.Size(m)
}
func (m *Job_Skills) XXX_DiscardUnknown() {
	xxx_messageInfo_Job_Skills.DiscardUnknown(m)
}

var xxx_messageInfo_Job_Skills proto.InternalMessageInfo

func (m *Job_Skills) GetSkill() string {
	if m != nil {
		return m.Skill
	}
	return ""
}

func (m *Job_Skills) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "types.Job")
	proto.RegisterType((*Job_Skills)(nil), "types.Job.Skills")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4f, 0x86, 0x30,
	0x10, 0x86, 0x83, 0x7c, 0x14, 0x39, 0x26, 0x2f, 0x0e, 0x0d, 0x13, 0x71, 0xc2, 0xa5, 0x26, 0xea,
	0x2f, 0x70, 0x64, 0xc4, 0xcd, 0x8d, 0x62, 0xa3, 0x95, 0xd2, 0x6b, 0x68, 0x17, 0xfe, 0xbb, 0x83,
	0xf1, 0x00, 0xe3, 0xd6, 0xe7, 0x79, 0x9b, 0xf6, 0xde, 0x83, 0xea, 0x8b, 0xb4, 0x0a, 0x2b, 0x25,
	0xc2, 0x22, 0x6d, 0xc1, 0xc4, 0xbb, 0xef, 0x0c, 0xf2, 0x9e, 0x34, 0xde, 0x42, 0x91, 0x6c, 0x72,
	0x46, 0x66, 0x6d, 0xd6, 0x55, 0xc3, 0x0e, 0xd8, 0x42, 0xfd, 0x6e, 0xe2, 0xb4, 0xda, 0x90, 0x2c,
	0x79, 0x79, 0xc5, 0xd9, 0x7f, 0x85, 0x12, 0xca, 0x89, 0x96, 0x30, 0xfa, 0x4d, 0xe6, 0x9c, 0x9e,
	0x88, 0x08, 0x17, 0x47, 0x1f, 0x24, 0x2f, 0xac, 0xf9, 0xcc, 0xce, 0xfa, 0x59, 0x16, 0x87, 0xb3,
	0x7e, 0xc6, 0x06, 0xae, 0x1d, 0x4d, 0x23, 0x7f, 0x20, 0xd8, 0xff, 0x31, 0xde, 0x83, 0x88, 0xb3,
	0x75, 0x2e, 0xca, 0xb2, 0xcd, 0xbb, 0xfa, 0xf1, 0x46, 0xf1, 0xd4, 0xaa, 0x27, 0xad, 0x5e, 0x39,
	0x18, 0x8e, 0x0b, 0xcd, 0x33, 0x88, 0xdd, 0xfc, 0x56, 0x61, 0x77, 0x56, 0x61, 0xe0, 0x82, 0x9f,
	0x66, 0x31, 0x47, 0x89, 0x1d, 0x5e, 0xaa, 0xb7, 0x52, 0x3d, 0xf0, 0x9b, 0x5a, 0xf0, 0x5e, 0x9e,
	0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x6d, 0x3f, 0x50, 0x24, 0x01, 0x00, 0x00,
}
